[package]
name = "myke"
version = "0.1.0"
authors = ["Florian Merz <flomerz@gmail.com>"]
build = "build.rs"

[dependencies]
yaml-rust = "^0.3.5"
itertools = "^0.5.9"
humantime = "^1.0.0"
regex = "^0.2"
glob = "^0.2.11"
term_size = "0.2.3"

[dependencies.liquid]
git = "https://github.com/cobalt-org/liquid-rust.git"

[dependencies.lazytable]
git = "https://github.com/fiji-flo/lazytable.git"

[dependencies.capture]
path = "capture"

[build-dependencies]
glob = "^0.2.11"
itertools = "^0.5.9"
tempdir = "0.3"
