[package]
name = "myke"
version = "0.1.0"
authors = ["Florian Merz <flomerz@gmail.com>"]
build = "build.rs"

[dependencies]
yaml-rust = "0.4"
itertools = "0.7"
humantime = "1"
regex = "0.2"
glob = "0.2"
term_size = "0.3"
gtmpl = { git = "https://github.com/fiji-flo/gtmpl-rust", branch = "func-revamp" }
gtmpl_value = { git = "https://github.com/fiji-flo/gtmpl_value", branch = "map-n-novalue" }
sprig = { git = "https://github.com/fiji-flo/sprig-rust", branch = "defaults" }

[dependencies.lazytable]
git = "https://github.com/fiji-flo/lazytable.git"

[dependencies.capture]
path = "capture"

[build-dependencies]
glob = "0.2"
itertools = "0"
tempdir = "0.3"
