[package]
name = "myke"
version = "0.1.0"
authors = ["Florian Merz <flomerz@gmail.com>"]

[dependencies]
yaml-rust = "*"
itertools = "0.5.9"
humantime = "1.0.0"
prettytable-rs = "^0.6"
regex = "0.2"
glob = "0.2.11"
